### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [shojchi/kinozal_project#1]
1)
здесь посмотрите, чтобы не было разрывов полей
![image](https://user-images.githubusercontent.com/8464662/91441470-f0174d80-e878-11ea-9a55-88357364c2df.png)

**Comment by Alecto** [comment]
2)
ошибки валидации 5-6
![image](https://user-images.githubusercontent.com/8464662/91441588-29e85400-e879-11ea-9314-170aebe8771a.png)

на странице page
![image](https://user-images.githubusercontent.com/8464662/91441628-3c628d80-e879-11ea-9b73-567c5921bf84.png)

**Comment by shojchi** [comment]
@Alecto исправил замечания.

**Comment by shojchi** [comment]
repository: https://github.com/shojchi/grid-template_project
Git Pages: https://shojchi.github.io/grid-template_project/
grid-template project completed.

сб, 29 серп. 2020 о 21:11 Andrey <notifications@github.com> пише:
